"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.route = void 0;
var category_1 = require("./category/category");
var express_ext_1 = require("express-ext");
var multer_1 = __importDefault(require("multer"));
var security_express_1 = require("security-express");
var film_1 = require("./film/film");
var cinema_1 = require("./cinema/cinema");
function route(app, ctx, secure) {
    var parser = (0, multer_1.default)();
    app.get('/health', ctx.health.check);
    // app.get('/healthcheck', ctx.health2.check);
    app.patch('/log', ctx.log.config);
    app.patch('/middleware', ctx.middleware.config);
    app.post('/authenticate', parser.none(), ctx.authentication.authenticate);
    var readRole = ctx.authorize('role', security_express_1.read);
    var writeRole = ctx.authorize('role', security_express_1.write);
    (0, security_express_1.get)(app, '/privileges', readRole, ctx.privilege.all, secure);
    (0, security_express_1.put)(app, '/roles/:id/assign', writeRole, ctx.role.assign, secure);
    (0, security_express_1.get)(app, '/roles', readRole, ctx.role.search, secure);
    (0, security_express_1.post)(app, '/roles/search', readRole, ctx.role.search, secure);
    (0, security_express_1.get)(app, '/roles/search', readRole, ctx.role.search, secure);
    (0, security_express_1.get)(app, '/roles/:id', readRole, ctx.role.load, secure);
    (0, security_express_1.post)(app, '/roles', writeRole, ctx.role.create, secure);
    (0, security_express_1.put)(app, '/roles/:id', writeRole, ctx.role.update, secure);
    (0, security_express_1.patch)(app, '/roles/:id', writeRole, ctx.role.patch, secure);
    (0, security_express_1.del)(app, '/roles/:id', writeRole, ctx.role.delete, secure);
    var readUser = ctx.authorize('user', security_express_1.read);
    var writeUser = ctx.authorize('user', security_express_1.write);
    (0, security_express_1.get)(app, '/users', readUser, ctx.user.all, secure);
    (0, security_express_1.post)(app, '/users/search', readUser, ctx.user.search, secure);
    (0, security_express_1.get)(app, '/users/search', readUser, ctx.user.search, secure);
    (0, security_express_1.get)(app, '/users/:id', readUser, ctx.user.load, secure);
    (0, security_express_1.post)(app, '/users', writeUser, ctx.user.create, secure);
    (0, security_express_1.put)(app, '/users/:id', writeUser, ctx.user.update, secure);
    (0, security_express_1.patch)(app, '/users/:id', writeUser, ctx.user.patch, secure);
    (0, security_express_1.del)(app, '/users/:id', writeUser, ctx.user.delete, secure);
    var readAuditLog = ctx.authorize('audit_log', security_express_1.read);
    (0, security_express_1.get)(app, '/audit-logs', readAuditLog, ctx.auditLog.search, secure);
    (0, security_express_1.get)(app, '/audit-logs/search', readAuditLog, ctx.auditLog.search, secure);
    (0, security_express_1.post)(app, '/audit-logs/search', readAuditLog, ctx.auditLog.search, secure);
    var checkCategory = (0, express_ext_1.check)(category_1.categoryModel);
    var checkFilm = (0, express_ext_1.check)(film_1.filmModel);
    var checkFilmRate = (0, express_ext_1.check)(film_1.filmRateModel);
    var checkCinemaRate = (0, express_ext_1.check)(cinema_1.cinemaRateModel);
    var checkCinema = (0, express_ext_1.check)(cinema_1.cinemaModel);
    app.get('/categories', ctx.category.all);
    app.post('/categories', checkCategory, ctx.category.create);
    app.get('/categories/search', checkCategory, ctx.category.search);
    app.get('/categories/:id', ctx.category.load);
    app.put('/categories/:id', checkCategory, ctx.category.update);
    app.patch('/categories/:id', checkCategory, ctx.category.patch);
    app.delete('/categories/:id', checkCategory, ctx.category.delete);
    app.get('/films', ctx.film.all);
    app.post('/films', checkFilm, ctx.film.create);
    app.get('/films/search', checkFilm, ctx.film.search);
    app.post('/films/search', checkFilm, ctx.film.search);
    app.get('/films/:id', ctx.film.load);
    app.put('/films/:id', checkFilm, ctx.film.update);
    app.patch('/films/:id', checkFilm, ctx.film.patch);
    app.delete('/films/:id', checkFilm, ctx.film.delete);
    app.post('/films/rate', checkFilmRate, ctx.film.rate);
    app.post('/film-rate/search', ctx.filmRate.search);
    app.get('/film-rate/search', ctx.filmRate.search);
    var readCinemaParent = ctx.authorize('cinemaParent', security_express_1.read);
    var writeCinemaParent = ctx.authorize('cinemaParent', security_express_1.write);
    // get(app, '/cinemaParent', readCinemaParent, ctx.cinemaParent.all, secure);
    (0, security_express_1.post)(app, '/cinemaParent/search', readCinemaParent, ctx.cinemaParent.search, secure);
    (0, security_express_1.get)(app, '/cinemaParent/search', readCinemaParent, ctx.cinemaParent.search, secure);
    (0, security_express_1.get)(app, '/cinemaParent/:id', readCinemaParent, ctx.cinemaParent.load, secure);
    (0, security_express_1.post)(app, '/cinemaParent', writeCinemaParent, ctx.cinemaParent.create, secure);
    (0, security_express_1.put)(app, '/cinemaParent/:id', writeCinemaParent, ctx.cinemaParent.update, secure);
    (0, security_express_1.patch)(app, '/cinemaParent/:id', writeCinemaParent, ctx.cinemaParent.patch, secure);
    (0, security_express_1.del)(app, '/cinemaParent/:id', writeCinemaParent, ctx.cinemaParent.delete, secure);
    // const readCinema = ctx.authorize('cinema', read);
    // const writeCinema = ctx.authorize('cinema', write);
    // get(app, '/cinemaParent', readCinemaParent, ctx.cinemaParent.all, secure); 
    app.get('/cinema', ctx.cinema.all);
    app.post('/cinema', checkCinema, ctx.cinema.create);
    app.get('/cinema/search', checkCinema, ctx.cinema.search);
    app.post('/cinema/search', checkCinema, ctx.cinema.search);
    app.get('/cinema/:id', ctx.cinema.load);
    app.put('/cinema/:id', checkCinema, ctx.cinema.update);
    app.patch('/cinema/:id', checkCinema, ctx.cinema.patch);
    app.delete('/cinema/:id', checkCinema, ctx.cinema.delete);
    app.post('/cinema/rate', ctx.cinema.rate);
    app.post('/cinema-rate/search', ctx.cinemaRate.search);
    app.get('/cinema-rate/search', ctx.cinemaRate.search);
    var readRate = ctx.authorize('rate', security_express_1.read);
    var writeRate = ctx.authorize('rate', security_express_1.write);
    app.get('/rates', ctx.rate.all);
    app.post('/rate', ctx.rate.create);
    app.get('/rate', ctx.rate.load);
    app.get('/uploads', ctx.uploads.all);
    app.get('/uploads/:id', ctx.uploads.load);
    app.post('/uploads', parser.single('file'), ctx.uploads.upload);
    app.post('/uploads/youtube', ctx.uploads.insertData);
    app.delete('/uploads', ctx.uploads.remove);
    app.delete('/uploads/youtube', ctx.uploads.deleteData);
}
exports.route = route;
//# sourceMappingURL=route.js.map